version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: weekly
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: ssri
    versions:
    - 8.0.1
  - dependency-name: "@commitlint/cli"
    versions:
    - 12.0.1
  - dependency-name: "@commitlint/config-conventional"
    versions:
    - 12.0.1
  - dependency-name: "@babel/core"
    versions:
    - 7.13.13
  - dependency-name: eslint-plugin-jest
    versions:
    - 24.3.1
  - dependency-name: npm-check-updates
    versions:
    - 11.0.2
    - 11.1.1
    - 11.1.4
    - 11.1.9
    - 11.2.0
  - dependency-name: husky
    versions:
    - 5.0.9
  - dependency-name: "@babel/preset-typescript"
    versions:
    - 7.12.16
  - dependency-name: "@types/node"
    versions:
    - 14.14.28
  - dependency-name: "@babel/cli"
    versions:
    - 7.12.16
  - dependency-name: "@babel/preset-env"
    versions:
    - 7.12.16
  commit-message:
    prefix: chore
    include: scope
